Add a new rule creation guide
wrike/dart-code-metrics pull request #182
Opened 2020-12-26 18:47 UTC by incendial

### What is the purpose of this pull request? (put an "X" next to an item)

[X] Documentation update
[ ] Bug fix
[ ] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### What changes did you make? (Give an overview)
Closes #75 , Updates #147

2020-12-26 18:48 UTC, incendial commented
@dkrutskikh @Anrock what do u think? Seems enough to me, but i'am a bit biased.

2020-12-27 12:57 UTC, Anrock commented
@incendial LGTM. I don't think we need separate doc file for now. Maybe later when there is more docs on contributing.

2020-12-27 12:57 UTC, Anrock approved these changes

2020-12-27 12:58 UTC, Anrock commented
Oh, maybe add a link / mention CONTRIBUTING file in readme also?

2020-12-27 16:49 UTC, incendial commented
@Anrock done

2020-12-27 17:38 UTC, Anrock approved these changes

2020-12-28 16:41 UTC, dkrutskikh requested changes

2020-12-28 16:41 UTC, dkrutskikh commented on CONTRIBUTING.md
> +                lit))
@incendial missing trailing comma ?

2020-12-28 17:09 UTC, incendial commented on CONTRIBUTING.md
> +                lit))
it's an example, imo doesn't matter

2020-12-28 17:37 UTC, merged